module.exports = {
    user: "ebd1es82282",
    password: "Qmtwn10",
    connectString:"(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.12.48)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=xe)))"
};

// VPN = "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.12.48)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=xe)))"
// PUC = "(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ceatudb02)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SID=xe)))"